apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ricsc2/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 500m
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 20
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
        - name: Mongo__User
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: mongodb-secret
        - name: Mongo__Password
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongodb-secret
      imagePullSecrets:
        - name: acr-kubedev